### ISSUE TITLE
Redesign the character select menu.

### ISSUE THREAD

**Issue by catoidi** [catoidi/box-party-demo#4]
I'll preface this one by saying this is outside of my scope.

I like the character portraits I've made for each of the characters. Only problem is, if there's more than 6 characters, the portraits won't show up anymore. I'd like to change this.

**Comment by idiotbitz** [comment]
After redoing the BIGFONT, the character select menu is now able to hold up to 12 characters.

However, I'm keeping this issue up because I have ideas for more characters, but I'd like to find a way to lock characters behind CVARs before adding them, so that they could be tied to unlocks. 

I'd prefer to not overwhelm the player with too many options at once.

**Comment by catoidi** [comment]
the new game menu is now completely replaced in Demo v1.5, thanks to a backport of the menu from DI.
